<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BINTERNS-QA33L" failures="1" tests="15" name="Test.CustomerLoginTest" time="84.549" errors="0" timestamp="2023-05-15T15:21:28 IST" skipped="0">
  <testcase classname="Test.CustomerLoginTest" name="navigate_to_homepage_click_on_signin" time="2.371"/>
  <system-out/>
  <testcase classname="Test.CustomerLoginTest" name="visibility_customer_login_header" time="0.043"/>
  <system-out/>
  <testcase classname="Test.CustomerLoginTest" name="visibility_registered_customers_header" time="0.022"/>
  <system-out/>
  <testcase classname="Test.CustomerLoginTest" name="verify_label_email_on_page" time="0.019"/>
  <system-out/>
  <testcase classname="Test.CustomerLoginTest" name="verify_label_password_on_page" time="0.024"/>
  <system-out/>
  <testcase classname="Test.CustomerLoginTest" name="visibility_try_demo_customer_access_dialog" time="0.020"/>
  <system-out/>
  <testcase classname="Test.CustomerLoginTest" name="createanaccountbutton_redirection" time="8.238"/>
  <system-out/>
  <testcase classname="Test.CustomerLoginTest" name="forgotyourpasswordbutton_redirection" time="10.910">
    <failure message="expected [Forgot Your Password?] but found [Customer Login]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Forgot Your Password?] but found [Customer Login]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Test.CustomerLoginTest.forgotyourpasswordbutton_redirection(CustomerLoginTest.java:195)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- forgotyourpasswordbutton_redirection -->
  <system-out/>
  <testcase classname="Test.CustomerLoginTest" name="sign_in_with_invalid_credentials" time="10.108"/>
  <system-out/>
  <testcase classname="Test.CustomerLoginTest" name="sign_in_with_invalid_email" time="11.953"/>
  <system-out/>
  <testcase classname="Test.CustomerLoginTest" name="sign_in_with_invalid_password" time="15.047"/>
  <system-out/>
  <testcase classname="Test.CustomerLoginTest" name="sign_in_with_blank_email" time="6.647"/>
  <system-out/>
  <testcase classname="Test.CustomerLoginTest" name="sign_in_with_Blank_password" time="9.974"/>
  <system-out/>
  <testcase classname="Test.CustomerLoginTest" name="sign_in_with_Blank_credentials" time="2.311"/>
  <system-out/>
  <testcase classname="Test.CustomerLoginTest" name="sign_in_with_valid_credentials" time="6.862"/>
  <system-out/>
</testsuite> <!-- Test.CustomerLoginTest -->
